TTIEX355P Bug fixing
ISISComputingGroup/EPICS-ioc pull request #612
Opened 2021-04-15 10:07 UTC by JamesKingWork

### Description of work

TTIEX355P:

- Correct range controls to use DRVH and DRVL rather than HOPR and LOPR
- Autosave setpoints if macro set

### To test

https://github.com/ISISComputingGroup/IBEX/issues/6397

### Acceptance criteria

*List the acceptance criteria for the PR*

---

#### Code Review

- [ ] A copy of the manual has been placed on the shared drive
- [ ] Pertitent information has been stored in the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC)
- [ ] Does the IOC conform to IBEX standards?
    - [PV naming](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
    - [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records)
    - [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)
    - [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)?
- [ ] Do the IOC and support module conform to the new [build guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reducing-Build-Dependencies)
- [ ] Have the changes been recorded appropriately in a PR for [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?
- [ ] Is the device's flow control setting correct? [For most devices flow control should be OFF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Flow-control).

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Supplementary IOCs (`..._0n` where `n>1`) run correctly
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

### Final steps

- [ ] Update the IOC submodule in the main EPICS repo. See [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has merged the associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-04-15 16:23 UTC, FreddieAkeroyd commented on TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/st.cmd
> +
Do you need "DO" ?  I feel  `IFAUTOSAVESETPOINTS`   sounds nicer than   `IFDOAUTOSAVESETPOINTS`

2021-04-15 16:24 UTC, FreddieAkeroyd commented on TTIEX355P/TTIEX355P-IOC-01App/Db/ttiEX355P.db
>  }
Would it be worth defaulting this e.g. $(IFAUTOSAVESETPOINTS=#)

2021-04-19 17:22 UTC, DominicOram requested changes
I agree with @FreddieAkeroyd's comments. Otherwise looks good!

2021-05-24 18:13 UTC, DominicOram approved these changes
Looks good, thanks

2021-05-24 18:16 UTC, merged