Ticket5874 add ioc technix
ISISComputingGroup/EPICS-ioc pull request #681
Opened 2022-04-08 15:19 UTC by daryakoskeroglu

### Description of work

IOC master Technix PSU

### Acceptance criteria

1. The Technix IOC must allow me to control the following variables:
voltage
current
HV status
Local/Remote Status
2. The OPI must display the following fields:
voltage
current
HV status
Local/Remote Status
Fault status
Interlock status
3. I can control the Technix PSU via genie_python scripts.
4. IBEX must support at least 6 Technix IOC instances.

---

#### Code Review

- [ ] A copy of the manual has been placed on the shared drive
- [ ] Pertitent information has been stored in the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC)
- [ ] Does the IOC conform to IBEX standards?
    - [PV naming](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
    - [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records)
    - [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)
    - [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)?
- [ ] Do the IOC and support module conform to the new [build guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reducing-Build-Dependencies)
- [ ] Have the changes been recorded appropriately in a PR for [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?
- [ ] Is the device's flow control setting correct? [For most devices flow control should be OFF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Flow-control).

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Supplementary IOCs (`..._0n` where `n>1`) run correctly
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

### Final steps

- [ ] Update the IOC submodule in the main EPICS repo. See [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has merged the associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2022-04-11 10:17 UTC, FreddieAkeroyd commented
Hi, there seem to be some `FMR/.vs` files in the PR that look to have been added by accident?

2022-04-11 10:42 UTC, daryakoskeroglu commented
> Hi, there seem to be some `FMR/.vs` files in the PR that look to have been added by accident?

Hello, oh yes, I am not sure how it happened, I didn't add the files to the commit. Will fix it now, thanks!

2022-05-17 22:01 UTC, FreddieAkeroyd commented on TECHNIX/iocBoot/iocTECHNIX-IOC-01/config.xml
> +<macro name="MAX_CURR" pattern="^[0-9]+$" description="Maximum current" />
Do we need to allow for a decimal point in MAX_CURR pattern?

2022-05-23 12:54 UTC, SamJenkins1 requested changes
Its not obvious what the colours mean on some of the status indicators, it might be better to show rext similar to local/remote, or show colours that clearly show whether or not it can run (for example, green for mains status being true.) or honestly, both.

2022-05-30 14:11 UTC, SamJenkins1 approved these changes

2022-05-30 14:12 UTC, merged