Added script path macro to the Background Script IOC.
ISISComputingGroup/EPICS-ioc pull request #715
Opened 2022-08-09 14:07 UTC by NikolaRoev

### Description of work

Added a path macro to the Background Script IOC.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/5743

### Acceptance criteria

See ticket.

---

#### Code Review

- [ ] A copy of the manual has been placed on the shared drive
- [ ] Pertitent information has been stored in the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC)
- [ ] Does the IOC conform to IBEX standards?
    - [PV naming](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
    - [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records)
    - [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)
    - [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)?
- [ ] Do the IOC and support module conform to the new [build guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reducing-Build-Dependencies)
- [ ] Have the changes been recorded appropriately in a PR for [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?
- [ ] Is the device's flow control setting correct? [For most devices flow control should be OFF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Flow-control).

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Supplementary IOCs (`..._0n` where `n>1`) run correctly
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

### Final steps

- [ ] Update the IOC submodule in the main EPICS repo. See [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has merged the associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2022-08-09 16:23 UTC, Tom-Willemsen requested changes

2022-08-09 16:23 UTC, Tom-Willemsen commented on BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/config.xml
> +    <macro name="SCRIPT_PATH" pattern="^.*$" description="Path to the Python background script." hasDefault="NO"/>
Would be useful to give a simple example or details of the default.

This also helps people to know whether they need to type `c:\something`, `c:/something`, or `c:\\something`

2022-08-09 16:23 UTC, Tom-Willemsen commented on BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/config.xml
> +    <macro name="SCRIPT_PATH" pattern="^.*$" description="Path to the Python background script." hasDefault="NO"/>
```suggestion
    <macro name="SCRIPT_PATH" pattern="^.*$" description="Path to the Python background script." hasDefault="YES"/>
```

This does have a default, doesn't it? The IOC boot script looks to say that if this isn't defined it defaults to `%ICPINSTSCRIPTROOT%/background_script.py`

2022-08-09 16:23 UTC, Tom-Willemsen commented on BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
>  setlocal
I think we also need to do a similar set of changes in this file for `BGRSCRPT_02`

2022-08-09 20:34 UTC, FreddieAkeroyd commented on BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
> +set "GETMACRO=C:\Instrument\Apps\EPICS\support\icpconfig\master\bin\%EPICS_HOST_ARCH%\icpconfigGetMacro.exe"
having run config_env_base you can use `%EPICS_KIT_ROOT%` instead of `C:\Instrument\Apps\EPICS`

2022-08-09 20:35 UTC, FreddieAkeroyd commented on BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
> -
instead of hard coding  `C:\Instrument\Apps\EPICS` in the file  i think
`call %~dp0..\..\..\..\..\config_env_base.bat` will work

2022-08-10 16:22 UTC, Tom-Willemsen commented on BGRSCRPT/settings/bgrscrpt_script.py
> +os.mkdir("C:\\Instrument\\Var\\tmp\\BGRSCRPT_01_test_dir")
```suggestion
os.mkdir(os.path.join("C:\\", "Instrument", "Var", "tmp", "BGRSCRPT_01_test_dir"))
```

2022-08-16 17:16 UTC, Tom-Willemsen approved these changes

2022-08-16 17:16 UTC, merged